services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - ${MARKETPLACE_DATABASE_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${MARKETPLACE_DATABASE_USER}
      POSTGRES_PASSWORD: ${MARKETPLACE_DATABASE_PASSWORD}
      POSTGRES_DB: ${MARKETPLACE_DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql
volumes:
  db:
    driver: local
